version: "3"

services:
  qbittorrent:
    image: linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Shanghai
    volumes:
      - ./qbittorrent:/config
      - ~/Media:/Media:rw
    network_mode: host
    restart: unless-stopped   

  flaresolverr:
    # DockerHub mirror flaresolverr/flaresolverr:latest
    image: ghcr.io/flaresolverr/flaresolverr:latest
    container_name: flaresolverr
    environment:
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - LOG_HTML=${LOG_HTML:-false}
      - CAPTCHA_SOLVER=${CAPTCHA_SOLVER:-none}
      - TZ=Asia/Shanghai
    network_mode: host
    ports:
      - "${PORT:-8191}:8191"
    restart: unless-stopped

  jackett:
    image: lscr.io/linuxserver/jackett:latest
    container_name: jackett
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Shanghai
    volumes:
      - ./jackett:/config
      - ~/Media:/Media:rw
    ports:
      - 9117:9117
    network_mode: host
    restart: unless-stopped   

      #  prowlarr:
      #    image: lscr.io/linuxserver/prowlarr:latest
      #    container_name: prowlarr
      #    environment:
      #      - PUID=1000
      #      - PGID=1000
      #      - TZ=Asia/Shanghai
      #    volumes:
      #      - ./prowlarr:/config
      #    ports:
      #      - 9696:9696
      #    network_mode: host
      #    restart: unless-stopped

  radarr:
    image: linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Shanghai
    volumes:
      - ./radarr:/config
      - ~/Media:/Media:rw
    ports:
      - 7878:7878
    network_mode: host
    restart: unless-stopped

  sonarr:
    image: ghcr.io/linuxserver/sonarr:develop-version-4.0.0.738
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Shanghai
    volumes:
      - ./sonarr:/config
      - ~/Media:/Media:rw
      - ~/Public:/Public:rw
        # - /home/wutm/Projects/Sonarr/_output/net6.0/linux-musl-x64:/app/sonarr/bin
    ports:
      - 8989:8989
    network_mode: host
    restart: unless-stopped   

  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    environment:
      - UID=1000
      - GID=1000
      - TZ=Asia/Shanghai
        # - GIDLIST=100 # A comma-separated list of additional GIDs to run emby as (default: 2)
    volumes:
      - ./jellyfin/config:/config
      - ./jellyfin/Cache:/cache
      - ~/Media:/Media:rw
    network_mode: host
    restart: unless-stopped

  bazarr:
    image: lscr.io/linuxserver/bazarr:latest
    container_name: bazarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Shanghai
    volumes:
      - ./bazarr/config:/config
      - ~/Media:/Media:rw
    network_mode: host
      # ports:
      # - 6767:6767
    restart: unless-stopped


      #  AutoBangumi:
      #    image: "ghcr.io/estrellaxd/auto_bangumi:latest"
      #    container_name: AutoBangumi
      #    volumes:
      #      - ./AutoBangumi/config:/app/config
      #      - ./AutoBangumi/data:/app/data
      #    ports:
      #      - "7892:7892"
      #    network_mode: host
      #    restart: unless-stopped
      #    dns:
      #      - 223.5.5.5
      #    environment:
      #      - TZ=Asia/Shanghai
      #      - PGID=1000
      #      - PUID=1000
      #      - UMASK=022

      #  chinesesubfinder:
      #    image: allanpk716/chinesesubfinder:latest
      #    volumes:
      #      - ./chineseSubFinder/config:/config
      #      - ./chineseSubFinder/browser:/root/.cache/rod/browser    # 容器重启后无需再次下载 chrome，除非 go-rod 更新
      #      - ~/Media:/media:rw
      #    environment:
      #      - PUID=1000         # uid
      #      - PGID=1000          # gid
      #      - PERMS=false        # 是否重设/media权限
      #      - TZ=Asia/Shanghai  # 时区
      #      - UMASK=022         # 权限掩码
      #    restart: always
      #    network_mode: host
      #    hostname: chinesesubfinder
      #    container_name: chinesesubfinder
      #    ports:
      #      - 19035:19035  # 从0.20.0版本开始，通过webui来设置
      #      - 19037:19037  # webui 的视频列表读取图片用，务必设置不要暴露到外网
      #    logging:
      #        driver: "json-file"
      #        options:
      #          max-size: "100m" # 限制docker控制台日志大小，可自行调整
